# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' SIS Simulator
#' 
#' This function simulates data according to the 
#' susceptible-infected-susceptible (SIS) 
#' compartmental model.
#' 
#' @param max_time Integer. Number of days to simulate.
#' @param initial 1xn binary vector indicating initially infected individuals.
#' @param A_mat Sparse adjacency matrix.
#' @param beta positive double. Transmission parameter.
#' @param days_infectious integer.  Number of days an individual remains infectious.
#' @return 
#' @export T x n matrix providing which individuals were infected at each 
#' time point.
sis_simulator <- function(max_time, initial, A_mat, beta, days_infectious) {
    .Call(`_networkPooledTesting_sis_simulator`, max_time, initial, A_mat, beta, days_infectious)
}

